[build-system]
# Should be mirrored in requirements.txt
requires = [
    "decorator",
    "packaging",
    "pip",
    "setuptools>=64",
    "setuptools-scm>=8",
    "wheel",
]
build-backend = "setuptools.build_meta"
